version: "3.0"

services:
    mongodb: # Este nombre es un nombre de red que permite atacar a este contenedor desde otros
        container_name: mimongo
        image: mongo:latest
        #restart: always
        ports:
            - 27017:27017
        environment:
            #- MONGO_INITDB_ROOT_USERNAME=usuario
            #- MONGO_INITDB_ROOT_PASSWORD=password
            MONGO_INITDB_ROOT_USERNAME: usuario
            MONGO_INITDB_ROOT_PASSWORD: password
            
    mongo-express:
        image: mongo-express:latest
        container_name: mimongoexpress
        #restart: always
        ports:
            - 8080:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: usuario
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_URL: mongodb://usuario:password@mongodb:27017/

# docker-compose up -d    
# docker-compose down 